package com.chance.database;

// Generated 2013-7-9 14:38:41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CFriend generated by hbm2java
 */
@Entity
@Table(name = "C_Friend", catalog = "chance")
public class CFriend implements java.io.Serializable {

	private Long CFriendId;
	private int CFriendSelfCid;
	private String CFriendGps;
	private long CFriendAddTime;
	private int CFriendFriendCid;
	private Long sequenceValue;

	public CFriend() {
	}

	public CFriend(int CFriendSelfCid, long CFriendAddTime, int CFriendFriendCid) {
		this.CFriendSelfCid = CFriendSelfCid;
		this.CFriendAddTime = CFriendAddTime;
		this.CFriendFriendCid = CFriendFriendCid;
	}

	public CFriend(int CFriendSelfCid, String CFriendGps, long CFriendAddTime,
			int CFriendFriendCid, Long sequenceValue) {
		this.CFriendSelfCid = CFriendSelfCid;
		this.CFriendGps = CFriendGps;
		this.CFriendAddTime = CFriendAddTime;
		this.CFriendFriendCid = CFriendFriendCid;
		this.sequenceValue = sequenceValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "C_Friend_ID", unique = true, nullable = false)
	public Long getCFriendId() {
		return this.CFriendId;
	}

	public void setCFriendId(Long CFriendId) {
		this.CFriendId = CFriendId;
	}

	@Column(name = "C_Friend_SelfCID", nullable = false)
	public int getCFriendSelfCid() {
		return this.CFriendSelfCid;
	}

	public void setCFriendSelfCid(int CFriendSelfCid) {
		this.CFriendSelfCid = CFriendSelfCid;
	}

	@Column(name = "C_Friend_Gps", length = 50)
	public String getCFriendGps() {
		return this.CFriendGps;
	}

	public void setCFriendGps(String CFriendGps) {
		this.CFriendGps = CFriendGps;
	}

	@Column(name = "C_Friend_AddTime", nullable = false)
	public long getCFriendAddTime() {
		return this.CFriendAddTime;
	}

	public void setCFriendAddTime(long CFriendAddTime) {
		this.CFriendAddTime = CFriendAddTime;
	}

	@Column(name = "C_Friend_FriendCID", nullable = false)
	public int getCFriendFriendCid() {
		return this.CFriendFriendCid;
	}

	public void setCFriendFriendCid(int CFriendFriendCid) {
		this.CFriendFriendCid = CFriendFriendCid;
	}

	@Column(name = "SEQUENCE_VALUE")
	public Long getSequenceValue() {
		return this.sequenceValue;
	}

	public void setSequenceValue(Long sequenceValue) {
		this.sequenceValue = sequenceValue;
	}

}
