package com.chance.database;

// Generated 2013-7-9 14:38:41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CUserInfo generated by hbm2java
 */
@Entity
@Table(name = "C_UserInfo", catalog = "chance")
public class CUserInfo implements java.io.Serializable {

	private Integer CUserInfoId;
	private String CUserInfoNickName;
	private Integer CUserInfoSex;
	private long CUserInfoBirthday;
	private String CUserInfoHeight;
	private String CUserInfoConstellation;
	private String CUserInfoBloodType;
	private String CUserInfoNation;
	private String CUserInfoCity;
	private String CUserInfoSchool;
	private String CUserInfoInterest;
	private String CUserInfoOccupation;
	private String CUserInfoState;
	private String CUserInfoPic;
	private String CUserInfoRealName;
	private String CUserInfoAffiliation;
	private String CUserInfoHomepage;
	private Integer CUserInfoMood;
	private Integer CUserInfoFlag;
	private Integer CUserInfoSetBirthday;
	private Integer CUserInfoSetOccupation;
	private Integer CUserInfoSetInterest;
	private Integer CUserInfoSetAffiliation;
	private Integer CUserInfoSetRealName;
	private Integer CUserInfoSetState;
	private Integer CUserInfoSetBloodType;
	private String CUserInfoStatus;
	private Long id;
	private Integer CUserInfoSetShareMapAddr;

	public CUserInfo() {
	}

	public CUserInfo(String CUserInfoNickName, long CUserInfoBirthday,
			String CUserInfoConstellation) {
		this.CUserInfoNickName = CUserInfoNickName;
		this.CUserInfoBirthday = CUserInfoBirthday;
		this.CUserInfoConstellation = CUserInfoConstellation;
	}

	public CUserInfo(String CUserInfoNickName, Integer CUserInfoSex,
			long CUserInfoBirthday, String CUserInfoHeight,
			String CUserInfoConstellation, String CUserInfoBloodType,
			String CUserInfoNation, String CUserInfoCity,
			String CUserInfoSchool, String CUserInfoInterest,
			String CUserInfoOccupation, String CUserInfoState,
			String CUserInfoPic, String CUserInfoRealName,
			String CUserInfoAffiliation, String CUserInfoHomepage,
			Integer CUserInfoMood, Integer CUserInfoFlag,
			Integer CUserInfoSetBirthday, Integer CUserInfoSetOccupation,
			Integer CUserInfoSetInterest, Integer CUserInfoSetAffiliation,
			Integer CUserInfoSetRealName, Integer CUserInfoSetState,
			Integer CUserInfoSetBloodType, String CUserInfoStatus, Long id,
			Integer CUserInfoSetShareMapAddr) {
		this.CUserInfoNickName = CUserInfoNickName;
		this.CUserInfoSex = CUserInfoSex;
		this.CUserInfoBirthday = CUserInfoBirthday;
		this.CUserInfoHeight = CUserInfoHeight;
		this.CUserInfoConstellation = CUserInfoConstellation;
		this.CUserInfoBloodType = CUserInfoBloodType;
		this.CUserInfoNation = CUserInfoNation;
		this.CUserInfoCity = CUserInfoCity;
		this.CUserInfoSchool = CUserInfoSchool;
		this.CUserInfoInterest = CUserInfoInterest;
		this.CUserInfoOccupation = CUserInfoOccupation;
		this.CUserInfoState = CUserInfoState;
		this.CUserInfoPic = CUserInfoPic;
		this.CUserInfoRealName = CUserInfoRealName;
		this.CUserInfoAffiliation = CUserInfoAffiliation;
		this.CUserInfoHomepage = CUserInfoHomepage;
		this.CUserInfoMood = CUserInfoMood;
		this.CUserInfoFlag = CUserInfoFlag;
		this.CUserInfoSetBirthday = CUserInfoSetBirthday;
		this.CUserInfoSetOccupation = CUserInfoSetOccupation;
		this.CUserInfoSetInterest = CUserInfoSetInterest;
		this.CUserInfoSetAffiliation = CUserInfoSetAffiliation;
		this.CUserInfoSetRealName = CUserInfoSetRealName;
		this.CUserInfoSetState = CUserInfoSetState;
		this.CUserInfoSetBloodType = CUserInfoSetBloodType;
		this.CUserInfoStatus = CUserInfoStatus;
		this.id = id;
		this.CUserInfoSetShareMapAddr = CUserInfoSetShareMapAddr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "C_UserInfo_ID", unique = true, nullable = false)
	public Integer getCUserInfoId() {
		return this.CUserInfoId;
	}

	public void setCUserInfoId(Integer CUserInfoId) {
		this.CUserInfoId = CUserInfoId;
	}

	@Column(name = "C_UserInfo_NickName", nullable = false, length = 20)
	public String getCUserInfoNickName() {
		return this.CUserInfoNickName;
	}

	public void setCUserInfoNickName(String CUserInfoNickName) {
		this.CUserInfoNickName = CUserInfoNickName;
	}

	@Column(name = "C_UserInfo_Sex")
	public Integer getCUserInfoSex() {
		return this.CUserInfoSex;
	}

	public void setCUserInfoSex(Integer CUserInfoSex) {
		this.CUserInfoSex = CUserInfoSex;
	}

	@Column(name = "C_UserInfo_Birthday", nullable = false)
	public long getCUserInfoBirthday() {
		return this.CUserInfoBirthday;
	}

	public void setCUserInfoBirthday(long CUserInfoBirthday) {
		this.CUserInfoBirthday = CUserInfoBirthday;
	}

	@Column(name = "C_UserInfo_Height", length = 20)
	public String getCUserInfoHeight() {
		return this.CUserInfoHeight;
	}

	public void setCUserInfoHeight(String CUserInfoHeight) {
		this.CUserInfoHeight = CUserInfoHeight;
	}

	@Column(name = "C_UserInfo_Constellation", nullable = false, length = 20)
	public String getCUserInfoConstellation() {
		return this.CUserInfoConstellation;
	}

	public void setCUserInfoConstellation(String CUserInfoConstellation) {
		this.CUserInfoConstellation = CUserInfoConstellation;
	}

	@Column(name = "C_UserInfo_BloodType", length = 20)
	public String getCUserInfoBloodType() {
		return this.CUserInfoBloodType;
	}

	public void setCUserInfoBloodType(String CUserInfoBloodType) {
		this.CUserInfoBloodType = CUserInfoBloodType;
	}

	@Column(name = "C_UserInfo_Nation", length = 20)
	public String getCUserInfoNation() {
		return this.CUserInfoNation;
	}

	public void setCUserInfoNation(String CUserInfoNation) {
		this.CUserInfoNation = CUserInfoNation;
	}

	@Column(name = "C_UserInfo_City", length = 50)
	public String getCUserInfoCity() {
		return this.CUserInfoCity;
	}

	public void setCUserInfoCity(String CUserInfoCity) {
		this.CUserInfoCity = CUserInfoCity;
	}

	@Column(name = "C_UserInfo_School", length = 50)
	public String getCUserInfoSchool() {
		return this.CUserInfoSchool;
	}

	public void setCUserInfoSchool(String CUserInfoSchool) {
		this.CUserInfoSchool = CUserInfoSchool;
	}

	@Column(name = "C_UserInfo_Interest", length = 50)
	public String getCUserInfoInterest() {
		return this.CUserInfoInterest;
	}

	public void setCUserInfoInterest(String CUserInfoInterest) {
		this.CUserInfoInterest = CUserInfoInterest;
	}

	@Column(name = "C_UserInfo_Occupation", length = 50)
	public String getCUserInfoOccupation() {
		return this.CUserInfoOccupation;
	}

	public void setCUserInfoOccupation(String CUserInfoOccupation) {
		this.CUserInfoOccupation = CUserInfoOccupation;
	}

	@Column(name = "C_UserInfo_State", length = 20)
	public String getCUserInfoState() {
		return this.CUserInfoState;
	}

	public void setCUserInfoState(String CUserInfoState) {
		this.CUserInfoState = CUserInfoState;
	}

	@Column(name = "C_UserInfo_Pic")
	public String getCUserInfoPic() {
		return this.CUserInfoPic;
	}

	public void setCUserInfoPic(String CUserInfoPic) {
		this.CUserInfoPic = CUserInfoPic;
	}

	@Column(name = "C_UserInfo_RealName", length = 20)
	public String getCUserInfoRealName() {
		return this.CUserInfoRealName;
	}

	public void setCUserInfoRealName(String CUserInfoRealName) {
		this.CUserInfoRealName = CUserInfoRealName;
	}

	@Column(name = "C_UserInfo_Affiliation", length = 50)
	public String getCUserInfoAffiliation() {
		return this.CUserInfoAffiliation;
	}

	public void setCUserInfoAffiliation(String CUserInfoAffiliation) {
		this.CUserInfoAffiliation = CUserInfoAffiliation;
	}

	@Column(name = "C_UserInfo_Homepage", length = 50)
	public String getCUserInfoHomepage() {
		return this.CUserInfoHomepage;
	}

	public void setCUserInfoHomepage(String CUserInfoHomepage) {
		this.CUserInfoHomepage = CUserInfoHomepage;
	}

	@Column(name = "C_UserInfo_Mood")
	public Integer getCUserInfoMood() {
		return this.CUserInfoMood;
	}

	public void setCUserInfoMood(Integer CUserInfoMood) {
		this.CUserInfoMood = CUserInfoMood;
	}

	@Column(name = "C_UserInfo_Flag")
	public Integer getCUserInfoFlag() {
		return this.CUserInfoFlag;
	}

	public void setCUserInfoFlag(Integer CUserInfoFlag) {
		this.CUserInfoFlag = CUserInfoFlag;
	}

	@Column(name = "C_UserInfo_Set_Birthday")
	public Integer getCUserInfoSetBirthday() {
		return this.CUserInfoSetBirthday;
	}

	public void setCUserInfoSetBirthday(Integer CUserInfoSetBirthday) {
		this.CUserInfoSetBirthday = CUserInfoSetBirthday;
	}

	@Column(name = "C_UserInfo_Set_Occupation")
	public Integer getCUserInfoSetOccupation() {
		return this.CUserInfoSetOccupation;
	}

	public void setCUserInfoSetOccupation(Integer CUserInfoSetOccupation) {
		this.CUserInfoSetOccupation = CUserInfoSetOccupation;
	}

	@Column(name = "C_UserInfo_Set_Interest")
	public Integer getCUserInfoSetInterest() {
		return this.CUserInfoSetInterest;
	}

	public void setCUserInfoSetInterest(Integer CUserInfoSetInterest) {
		this.CUserInfoSetInterest = CUserInfoSetInterest;
	}

	@Column(name = "C_UserInfo_Set_Affiliation")
	public Integer getCUserInfoSetAffiliation() {
		return this.CUserInfoSetAffiliation;
	}

	public void setCUserInfoSetAffiliation(Integer CUserInfoSetAffiliation) {
		this.CUserInfoSetAffiliation = CUserInfoSetAffiliation;
	}

	@Column(name = "C_UserInfo_Set_RealName")
	public Integer getCUserInfoSetRealName() {
		return this.CUserInfoSetRealName;
	}

	public void setCUserInfoSetRealName(Integer CUserInfoSetRealName) {
		this.CUserInfoSetRealName = CUserInfoSetRealName;
	}

	@Column(name = "C_UserInfo_Set_State")
	public Integer getCUserInfoSetState() {
		return this.CUserInfoSetState;
	}

	public void setCUserInfoSetState(Integer CUserInfoSetState) {
		this.CUserInfoSetState = CUserInfoSetState;
	}

	@Column(name = "C_UserInfo_Set_BloodType")
	public Integer getCUserInfoSetBloodType() {
		return this.CUserInfoSetBloodType;
	}

	public void setCUserInfoSetBloodType(Integer CUserInfoSetBloodType) {
		this.CUserInfoSetBloodType = CUserInfoSetBloodType;
	}

	@Column(name = "C_UserInfo_Status")
	public String getCUserInfoStatus() {
		return this.CUserInfoStatus;
	}

	public void setCUserInfoStatus(String CUserInfoStatus) {
		this.CUserInfoStatus = CUserInfoStatus;
	}

	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "C_UserInfo_Set_ShareMapAddr")
	public Integer getCUserInfoSetShareMapAddr() {
		return this.CUserInfoSetShareMapAddr;
	}

	public void setCUserInfoSetShareMapAddr(Integer CUserInfoSetShareMapAddr) {
		this.CUserInfoSetShareMapAddr = CUserInfoSetShareMapAddr;
	}

}
